name: flutter_application_shoppingapp
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  badges: ^2.0.3
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono-Light.ttf
          weight: 300
    - family: RaleWay
      fonts:
        - asset: assets/fonts/RaleWay-Regular.ttf
        - asset: assets/fonts/RaleWay-Bold.ttf
          weight: 700
        - asset: assets/fonts/RaleWay-Light.ttf
          weight: 300
  assets:
    - assets/images/
